#!/bin/sh
if test $# -ne 1
then
	echo "Usage: sgml-tex sgml-file" 1>&2;
	exit 1
fi
awk "/<verb>/ {in_verb = 1;}
     /<\\/verb>/ {in_verb = 0;}
     {gsub (/&/,\"& \");\
      if (!in_verb) gsub (/#/,\"\\\\&num;\");\
      gsub (/\\$/,\"\\\\&dollar;\");print}" $*
exit 0
