#!/bin/sh
if test $# -ne 1
then
	echo "Usage: sgml-txt sgml-file" 1>&2;
	exit 1
fi
awk "{if (match (\$0, /<enum>/)) {enum_nest++;curr[enum_nest]=0;} \
      else if (match (\$0, /<itemize>/)) {enum_nest++;curr[enum_nest]=-1;} \
      else if (match (\$0, /<\/enum>/)) {enum_nest--;} \
      else if (match (\$0, /<\/itemize>/)) {enum_nest--;} \
      else if (enum_nest != 0 && curr[enum_nest] >= 0 && match (\$0, /<item>/)) {\
        curr[enum_nest]++;sub (/<item>/, curr[enum_nest] \". \");\
      } else {\
        gsub (/<item>/,\"o \");\
      }\
      gsub (/<tag>/,\"o \");\
      if (match (\$0, /<sect>/)) {\
        sect++;sub (/<sect>/, sect \". \");\
        sect1=0; sect2=0; sect3=0; sect4=0; sect5=0;\
      } else if (match (\$0, /<sect1>/)) {\
        sect1++;sub (/<sect1>/, sect \".\" sect1 \". \");\
        sect2=0; sect3=0; sect4=0; sect5=0;\
      } else if (match (\$0, /<sect2>/)) {\
        sect2++;sub (/<sect2>/, sect \".\" sect1 \".\" sect2 \". \");\
        sect3=0; sect4=0; sect5=0;\
      } else if (match (\$0, /<sect3>/)) {\
        sect3++;sub (/<sect3>/, sect \".\" sect1 \".\" sect2 \".\" sect3 \". \");\
        sect4=0; sect5=0;\
      } else if (match (\$0, /<sect4>/)) {\
        sect4++;sub (/<sect4>/, sect \".\" sect1 \".\" sect2 \".\" sect3 \".\" sect4 \". \");\
        sect5=0;\
      } else if (match (\$0, /<sect5>/)) {\
        sect5++;sub (/<sect5>/, sect \".\" sect1 \".\" sect2 \".\" sect3 \".\" sect4 \".\" sect5 \". \");\
      }\
      gsub (/<article>|<title>|<author>|<date>|<abstract>|<toc>|<p>|<tt>|<code>|<tscreen>|<verb>|<descrip>|<enum>|<itemize>|<bf>|<em>/,\"\");\
      gsub (/<\/[^>]+>/,\"\");\
      gsub (/<![^>]+>/,\"\");\
      gsub (/&amp;/,\"\\\\&\");gsub (/&lt;/,\"<\");\
      gsub (/&gt;/,\">\");gsub (/&etago;/,\"</\");gsub (/&dollar;/,\"\$\");\
      gsub (/&num;/,\"#\");gsub (/&percnt;/,\"%\");gsub (/&tilde;/,\"~\");\
      gsub (/&lsqb;/,\"[\");gsub (/&rsqb;/,\"]\");\
      gsub (/&lcub;/,\"{\");gsub (/&rcub;/,\"}\");\
      print}" $*
exit 0
